# Generated by Django 4.2.16 on 2024-11-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_level_alter_movie_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='level',
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
