# Generated by Django 4.2.16 on 2024-11-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviecomment_remove_movie_like_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
